### ISSUE TITLE
Option to edit my posts

### ISSUE THREAD

**Issue by anilmaurya** [rishijain/oneplaceaday#38]
I should have option to edit my posts after adding.

**Comment by rishijain** [comment]
there is. when you visit your posts show page, there is link to edit on the title of post. It takes you to edit page.

**Comment by anilmaurya** [comment]
Yes, it works. But it is not so obvious, may be something like a  tooltip will make it more clear.

**Comment by rishijain** [comment]
And finally the most dreaded day is here when somebody complained that it is not so obvious. I like the idea of adding a tool-tip. Will fix it :hammer:

**Comment by anilmaurya** [comment]
thanks :)

**Comment by rishijain** [comment]
We have added a button for edit which is not easy to miss. Also the old way of editing still exists. I think it is good to close this one. 👻  /cc: @anilmaurya
