### ISSUE TITLE
Geocoder request fails without any error messages

### ISSUE THREAD

**Issue by anilmaurya** [rishijain/oneplaceaday#64]
When I tried to publish a post on local server, I get this error on server logs:

Geocoder: HTTP request being made for http://maps.googleapis.com/maps/api/geocode/json?address=pune%2C+india&language=en&sensor=false
(0.3ms)  ROLLBACK
(0.3ms)  ROLLBACK

But no errors message is shown on browser.

This behaviour is confusing , I didn't understand why I am not able to publish posts until I saw my server logs.

**Comment by rishijain** [comment]
this was coming because validation failed. I am closing this one as I have filed another issue at #66 and #67 . Thanks for reporting. 👍
